#!/bin/bash

echo "🔍 Cloudinary Cloud Name Finder"
echo "================================"
echo ""
echo "To find your actual Cloudinary Cloud Name:"
echo ""
echo "1. Go to: https://cloudinary.com/console"
echo "2. Log in to your account"
echo "3. Look at the top-left of the dashboard"
echo "4. You'll see 'Cloud name: xxxxx'"
echo "5. Copy that exact value (it should be lowercase, no spaces)"
echo ""
echo "Your Cloud Name typically looks like:"
echo "  ✓ dxyz123456"
echo "  ✓ my-company-name"
echo "  ✓ user_name_cms"
echo ""
echo "NOT like:"
echo "  ✗ Omer Bhai CMS (has spaces)"
echo "  ✗ My Company (has spaces)"
echo ""
echo "Current value in .env: ${CLOUDINARY_CLOUD_NAME}"
echo ""
echo "Once you have the correct Cloud Name, update it in:"
echo "  backend/.env"
echo ""
echo "Or you can also find it in the URL when you're logged in:"
echo "  https://console.cloudinary.com/console/c-XXXXXX/..."
echo "  The part after 'c-' but before the next '/' might be a hash"
echo ""
echo "Alternative: Check the 'Account Details' section in Settings"
echo ""
